name: Zeebe Release Dry Run from stable branches
on:
  workflow_dispatch: { }
  schedule:
    # Runs at 02:00 every week day; see this link for more: https://crontab.guru/#0_2_*_*_1-5
    - cron: '0 2 * * 1-5'

jobs:
  dry-run-release-84:
    name: "Release from stable/8.4"
    uses: camunda/zeebe/.github/workflows/zeebe-release.yml@stable/8.4
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      releaseBranch: stable/8.4
      releaseVersion: 0.8.4
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: true
      dryRun: true
  dry-run-release-83:
    name: "Release from stable/8.3"
    uses: camunda/zeebe/.github/workflows/zeebe-release.yml@stable/8.3
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      releaseBranch: stable/8.3
      releaseVersion: 0.8.3
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: true
      dryRun: true
  dry-run-release-82:
    name: "Release from stable/8.2"
    uses: camunda/zeebe/.github/workflows/zeebe-release.yml@stable/8.2
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      releaseBranch: stable/8.2
      releaseVersion: 0.8.2
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: true
      dryRun: true
  dry-run-release-81:
    name: "Release from stable/8.1"
    uses: camunda/zeebe/.github/workflows/zeebe-release.yml@stable/8.1
    secrets: inherit
    strategy:
      fail-fast: false
    with:
      releaseBranch: stable/8.1
      releaseVersion: 0.8.1
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: false
      dryRun: true
  notify:
    name: Send slack notification
    runs-on: ubuntu-latest
    needs: [ dry-run-release-81, dry-run-release-82, dry-run-release-83 ]
    if: ${{ always() }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
      - id: slack-notify-failure
        name: Send failure slack notification
        uses: slackapi/slack-github-action@v1.25.0
        if: ${{ always() && (needs.dry-run-release-81.result != 'success' || needs.dry-run-release-82.result != 'success' || needs.dry-run-release-83.result != 'success') }}
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":alarm: *Release Dry Run* from `stable/*` failed! :alarm:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the related workflow execution: https://github.com/camunda/zeebe/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
      - id: slack-notify-success
        name: Send success slack notification
        uses: slackapi/slack-github-action@v1.25.0
        if: ${{ always() && needs.dry-run-release-81.result == 'success' && needs.dry-run-release-82.result == 'success' && needs.dry-run-release-83.result == 'success' }}
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":tada: *Release Dry Run* from `stable/*` succeeded! :tada:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Nothing to check today. Good job! :clap:\n"
                  }
                }
              ]
            }
